version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "project"
    volumes:
      - mysqldb_data:/var/lib/mysql
    ports:
      - "3307:3306" # Expose MySQL on the default port.
    networks:
      - internalnetwork

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server-container
    restart: unless-stopped
    ports:
      - "3000:3000" # Match the PORT in your .env file.
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: "127.0.0.1" # Use the host's network.
      MYSQL_PORT: 3306 # Changed to MySQL's default port.
      MYSQL_USER: "root"
      MYSQL_DATABASE: "project"
      MYSQL_ROOT_PASSWORD: "1234"
    network_mode: "host" # Use the host's network.

networks:
  internalnetwork:
    driver: bridge

volumes:
  mysqldb_data:
